### PR TITLE
048 User Control Updated code

### PR DESCRIPTION
**Pull request by KHerron**

### CODE REVIEW

**Comment by bwoodworth** [comment]
It looks like maybe you didn't have the latest version of the repository when making this pull request.  There are changes all over that don't look related

**Comment by KHerron** [comment]
I’m so sorry Brian, I am not very good with Github at all.

Every time I do a compare, it just does some crazy crap =).

 

As you can see, f3cfee6 is where I tried to get my repository up to date with the master….

Anyhow, you should really on be concerned with the last 2:

1abc333 & f6bc25d

 

Should I complexly remove my for, and try to Re-fork??

As my repository says I’m 8 commits ahead and 26 commits behind?

 

I just can’t get a grip on this…………. L

**Comment by bwoodworth** [comment]
No worries.  I still don't get a lot of the way Git works.  Is there a way to do a pull request for specific commits?

**Comment by KHerron** [comment]
I have no clue at all.

Like I said, I can delete my fork.
Then create a new Fork. This should make me UP-To-Date wit the master.

Then I can re-do my changes and create a new pull request.
If YES, you will need to delete my last pull request.

Let me know, what you want me to do.
I have no one forking from my repository, so it shouldn't effect anyone if we do it!

**Comment by bwoodworth** [comment]
Sounds good.  let's try that

**Comment by KHerron** [comment]
OK, Give it a try now!

 

Kirk Herron 
Project Manager 
(904)626-9854 
CCSG, Inc.

ES12000916 
http://www.ccsgweb.com <http://www.ccsgweb.com/>

**Pull request closed without merging**
